export const TECHNIQUES = [
  { value: 'T1', label: 'Casual Oversimplification' },
  { value: 'T2', label: 'Black-and-white Fallacy' },
  { value: 'T3', label: 'Straw Man' },
  { value: 'T4', label: 'Whataboutism' },
  { value: 'T5', label: 'Reductio ad Hitlerum' },
  { value: 'T6', label: 'Red Herring' },
  { value: 'T7', label: 'Loaded Language' },
  { value: 'T8', label: 'Name Calling and Labeling' },
  { value: 'T9', label: 'Appeal to fear/prejudice' },
  { value: 'T10', label: 'Slogans' },
  { value: 'T11', label: 'Flag-Waving' },
  { value: 'T12', label: 'Exaggeration and Minimization' },
  { value: 'T13', label: 'Thought-terminating Cliches' },
  { value: 'T14', label: 'Bandwagon' },
  { value: 'T15', label: 'Repetition' },
  { value: 'T16', label: 'Obfuscation, intentional vagueness, confusion' },
  { value: 'T17', label: 'Doubt' },
  { value: 'T18', label: 'Appeal to Authority' },
  { value: 'T19', label: 'Assertion' },
  { value: 'T20', label: 'Smears' },
  { value: 'T21', label: 'Glittering Generalities (Virtue)' },
];
